### ISSUE TITLE
[BUG] Immersive Portals crashes server

### ISSUE THREAD

**Issue by sirfredrick** [magmafoundation/Magma-1.15.x#11]
**Describe the bug**
A clear and concise description of what the bug is:
In the latest build of Magma 1.15.2 Alpha 1 (#79) with Forge Version 31.2.23, the Immersive Portals mod won't load and it crashes the server.
**To Reproduce**
1. Steps to reproduce the behavior:
2. Go to https://www.curseforge.com/minecraft/mc-mods/immersive-portals-for-forge
3. Download the 1.15.2 Version of Immersive Portals
4. Go to https://www.curseforge.com/minecraft/mc-mods/mixinbootstrap
5. Download the 1.15.2 Version of MixinBootstrap
6. In a new folder on your computer, install Magma Server 1.15.2 Alpha 1.
7. Start the server and once the world load stop it.
8. Put the Immersive Portals mod jar and the MixinBootstrap mod jar in the mods folder and restart.
9. The Magma Server should now crash with [this server log](https://mclo.gs/E8yJYKa).

**Expected behavior**
A clear and concise description of what you expected to happen:
I expected the server to be able to run this mod without crashing.
**Screenshots**
If applicable, add screenshots to help explain your problem:

**Info (please complete the following information):**
- Mod Name: Immersive Portals
 - Mod Version: 1.15.2_0.22
 - Magma Version: 1.15.2 Alpha 1 (Build #79)
 - OS: Pop!_OS 20.04 (Ubuntu 20.04) x64

**Additional context**
Add any other context about the problem here:
ImmersivePortals requires MixinBootstrap (I used 1.15.2_v1.0.3). I think the problem may be from the fact that Spigot Servers split the world file into three folders.

**Comment by kwright02** [comment]
This is an error with MixinBootstrap which is an unofficial way to load mixins. Because of this, and it's unreliability on regular forge, i'm closing this ticket.
