### ISSUE TITLE
Class error on log on

### ISSUE THREAD

**Issue by jahangir6969** [magmafoundation/Magma-1.15.x#17]
**Describe the bug**
A clear and concise description of what the bug is:

When any user log onto 1.15 it error out with a class error. 

**To Reproduce**
1. Get someone to log onto the server. 

**Expected behavior**
A clear and concise description of what you expected to happen:#

For it not to error out with the class when player/user connect to the server. 

**Screenshots**
If applicable, add screenshots to help explain your problem:

No screenshot needed check console. 

**Info (please complete the following information):**
Mod Name: Just the standard version on manga
Mod Version: 1.15.2
Magma Version: forge-1.15.2-31.2.23-b4c57d3.jar
OS: Ubuntu 20

**Additional context**
Add any other context about the problem here: https://pastebin.com/zmMAPFCz

**Comment by Hexeption** [comment]
Happens on Default Forge
