### ISSUE TITLE
End portal portal / end world not getting created correctly also server crashes when tping back

### ISSUE THREAD

**Issue by jahangir6969** [magmafoundation/Magma-1.15.x#21]
**Describe the bug**
A clear and concise description of what the bug is:

So when you create a portal it does not create end portals inside but let you tp to the end. Second issue is once it tp you to the end it does not spawn the end correctly and does not take you to the ender dragon.  Also when going back into the nether portal it crashes the server. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Create end portal and you will not see the end portal 
2. Once you create portal jump into it. 
3. Go into portal crashes server as well. 

**Expected behavior**
A clear and concise description of what you expected to happen:

For the end portal to show up and for it to create the END correctly and tp you to the dragon to fight it.  Also to fixes the crashing when Telport back to the normal world

**Screenshots**
If applicable, add screenshots to help explain your problem:

https://gyazo.com/06c134cd2e2d33147f0615350fe8c769

https://gyazo.com/0fd398c230f1830410cc85cb813ea0c1

https://gyazo.com/58011155485111f150b99ebb76e97828

**Info (please complete the following information):**
Mod Name: Just the standard version on manga
Mod Version: 1.15.2
Magma Version: forge-1.15.2-31.2.23-b4c57d3.jar
OS: Ubuntu 20

**Additional context**
Add any other context about the problem here: Here is the console error you get.  https://pastebin.com/4ig6wcbB

Here the crash log:  https://pastebin.com/LW7bVmDb

**Comment by jahangir6969** [comment]
*update*

So i have delete the world config and recreate the world and now tp me to the right world. 

But it not spawn the dragon or end crystal with heal the dragon and error alot in console. 

https://pastebin.com/XD30bs1k

**Comment by kwright02** [comment]
fixed issue in latest update.
