### ISSUE TITLE
Sword in creative Break blocks right away

### ISSUE THREAD

**Issue by jahangir6969** [magmafoundation/Magma-1.15.x#25]
**Describe the bug**
A clear and concise description of what the bug is:

Sword in creative break block right away when it should not

**To Reproduce**
1. Go to into creative and get a sword and start left clicking blocks. 

**Expected behavior**
A clear and concise description of what you expected to happen:

For it not to break block right away like it does in standard 1.15

**Screenshots**
If applicable, add screenshots to help explain your problem:

https://youtu.be/TcMjfLPk4rA

**Info (please complete the following information):**
Mod Name: Just the standard version on manga
Mod Version: 1.15.2
Magma Version: forge-1.15.2-31.2.23-b4c57d3.jar
OS: Ubuntu 20

**Additional context**
Add any other context about the problem here:

**Comment by kwright02** [comment]
fixed in next update.
