### ISSUE TITLE
Error joining nether

### ISSUE THREAD

**Issue by jahangir6969** [magmafoundation/Magma-1.15.x#30]
**Describe the bug**
A clear and concise description of what the bug is:

When going into the nether. It error alot out in console but it does not crash like the end. 

**To Reproduce**
1. Go to Enable nether and make a portal to go into.

**Expected behavior**
A clear and concise description of what you expected to happen:

For it not to spam console with error.

**Screenshots**
If applicable, add screenshots to help explain your problem:

No screenshot for this one. 

**Info (please complete the following information):**
Mod Name: Just the standard version on manga
Mod Version: 1.15.2
Magma Version: forge-1.15.2-31.2.23-b4c57d3.jar
OS: Ubuntu 20

**Additional context**
Add any other context about the problem here: Here is the console error.

**Comment by kwright02** [comment]
Can you upload a log of the error spam to https://mclo.gs

**Comment by jahangir6969** [comment]
https://pastebin.com/jgf7QN0H

**Comment by kwright02** [comment]
fixed in next update
