### ISSUE TITLE
2 bugs in one for the nether (Chat / Pickaxe issue)

### ISSUE THREAD

**Issue by jahangir6969** [magmafoundation/Magma-1.15.x#31]
**Describe the bug**
A clear and concise description of what the bug is:

So this is two issue for this ticket. The first issue is that when you enter the nether. You error out in chat saying "Cannot send Chat message" and when you go back into the normal world it stop working there as well. 

Second issue is when you trying to mine in the nether. Only pickaxes that works is gold pickaxe but the rest does not work. It does the mining anime but blocks it from being mined. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go into portal and try to send a chat message and also get all the pickaxes and tried to mine and you will see only gold with work. 

**Expected behavior**
A clear and concise description of what you expected to happen:

For the user to be able to send message in the nether or overworld/normal one. Also to be able to mine with any of the pickaxes and not just gold.

**Screenshots**
If applicable, add screenshots to help explain your problem:

https://youtu.be/MuKD37OLrnA

**Info (please complete the following information):**
Mod Name: Just the standard version on manga
Mod Version: 1.15.2
Magma Version: forge-1.15.2-31.2.23-b4c57d3.jar
OS: Ubuntu 20

**Additional context**
Add any other context about the problem here:

**Comment by kwright02** [comment]
I'm closing this issue because it's related to the previous issue of the end not working properly. This is directly tied to an issue with changing dimensions. For now, a way to work around this issue is to relog after going between dimensions.
