### ISSUE TITLE
Spam in console after changing level-type

### ISSUE THREAD

**Issue by jahangir6969** [magmafoundation/Magma-1.15.x#33]
**Describe the bug**
A clear and concise description of what the bug is:

It error in console alot with "[Server thread/WARN] [minecraft/EntityType]: Skipping Entity with id" After i delete the world folder and then changing level-type from flat to superbiome. Even since it error out in console even after regen the world folder and everything. 

**To Reproduce**
1. Change level-type to largeBiomes and watch console. 

**Expected behavior**
A clear and concise description of what you expected to happen:

For it not to spam console very few seconds. As you cannot see anything else. 

**Screenshots**
If applicable, add screenshots to help explain your problem:

https://gyazo.com/0c5d5882b6c77c030a2865186589e88c

**Info (please complete the following information):**
Mod Name: Just the standard version on manga
Mod Version: 1.15.2
Magma Version: forge-1.15.2-31.2.23-b4c57d3.jar
OS: Ubuntu 20

**Additional context**
Add any other context about the problem here:

**Comment by kwright02** [comment]
this doesn't happen anymore. Old bug.
