### ISSUE TITLE
[BUG] - Incompatability Immersive Portals/MixingBootstrap

### ISSUE THREAD

**Issue by SirOMGitsYOU** [magmafoundation/Magma-1.15.x#36]
**Describe the bug**
A clear and concise description of what the bug is:
Game is unable to launch when MixinBootstrap/Immersive Portals is installed.

**To Reproduce**
1. Install Immersive Portals & Mixing Bootstrap
2. Launch Server
3. Crash.

**Expected behaviour**
Game should load

**Screenshots**
n/a see log file

**Info (please complete the following information):**
- Mod Name: MixinBootstrap
 - Mod Version: 1.0.3
 - Magma Version: 1.15.2-31.2.23-1aa4b23
 - OS: Windows 10

[latest.log](https://github.com/magmafoundation/Magma-1.15.x/files/4933780/latest.log)
[debug.log](https://github.com/magmafoundation/Magma-1.15.x/files/4933782/debug.log)

**Comment by kwright02** [comment]
MixinBootstrap is unsupported
