### ISSUE TITLE
magma server comes up as "Incompatible vanilla server"

### ISSUE THREAD

**Issue by tanker122** [magmafoundation/Magma-1.15.x#37]
**Describe the bug**
A clear and concise description of what the bug is: Server comes up as "incompatible vanilla server" and when trying to connect anyway you get error.

**To Reproduce**
load up server and try to connect with latest forge

**Screenshots**
![Screenshot (3)](https://user-images.githubusercontent.com/40444856/87752847-2e1f4d00-c7b6-11ea-9efc-67f496d7e7f8.png)
![Screenshot (2)](https://user-images.githubusercontent.com/40444856/87752858-2fe91080-c7b6-11ea-83d0-059b53772a09.png)
![Screenshot (4)](https://user-images.githubusercontent.com/40444856/87820855-aec86280-c823-11ea-99c2-1b8ad7dd1129.png)

**Info (please complete the following information):**
- Mod Name:
 - Mod Version:  1.15.2
 - Magma Version:  Latest 1.15.2
 - OS: Windows 10 pro

**Additional context**
Client and server are running on same machine
https://mclo.gs/EXbfayb

**Comment by kwright02** [comment]
Did you install the client you're using from the magma installer?
