### ISSUE TITLE
[BUG] Quark and Quark Oddities crash server

### ISSUE THREAD

**Issue by sirfredrick** [magmafoundation/Magma-1.15.x#4]
**Describe the bug**
A clear and concise description of what the bug is:
In the latest build of Magma 1.15.2 Alpha 1 with Forge Version 31.2.0, the Quark mod (r2.1-245) won't load and it crashes the server.
**To Reproduce**
1. Go to https://www.curseforge.com/minecraft/mc-mods/quark
2. Download the 1.15.2 Version of Quark
3. Go to https://www.curseforge.com/minecraft/mc-mods/autoreglib
4. Download the 1.15.2 Version of AutoRegLib
3. In a new folder on your computer, install Magma Server 1.15.2 Alpha 1.
4. Start the server and once the world load stop it.
5. Put the Quark mod jar and the AutoRegLib in the mods folder and restart.
6. The Magma Server should now crash with [this server log](https://mclo.gs/zpptXwr).
**Expected behavior**
A clear and concise description of what you expected to happen:
I expected the server to be able to run this mod without crashing.
**Screenshots**
If applicable, add screenshots to help explain your problem:

**Info (please complete the following information):**
- Mod Name: Quark
 - Mod Version: 1.15.2_r2.1-245
 - Magma Version: 1.15.2 Alpha 1 (Build #73)
 - OS: Pop!_OS 20.04 (Ubuntu 20.04) x64

**Additional context**
Add any other context about the problem here:
Quark requires AutoRegLib (I used v1.5-40). Quark Oddities also doesn't work when added to the list but I think the problem is with the main Quark jar.

**Comment by Hexeption** [comment]
Fixed in 1760b12b3d8b559e733d3dc668fc69cdbd4e1cd8
