### ISSUE TITLE
Smithing table

### ISSUE THREAD

**Issue by jahangir6969** [magmafoundation/Magma-1.15.x#69]
**Describe the bug**
A clear and concise description of what the bug is:

Cannot even open smithing table/gui does not pop up

**To Reproduce**

Place smithing table and tried to open it 

**Expected behavior**
A clear and concise description of what you expected to happen:

For it to open GUI instead of doing nothing

**Screenshots**
If applicable, add screenshots to help explain your problem:

https://gyazo.com/3396a83d6e43c5ca6e612909f404097c

**Info (please complete the following information):**
Mod Name: Just the standard version on magma
Mod Version: 1.15.2
Magma Version: forge-1.15.2-31.2.23-aca6e8c.jar
OS: Ubuntu 20

**Additional context**
Add any other context about the problem here:

**Comment by Hexeption** [comment]
Smithing Table didn't get a UI till 1.16
