### ISSUE TITLE
When dying or getting killed it error out in console

### ISSUE THREAD

**Issue by jahangir6969** [magmafoundation/Magma-1.15.x#7]
**Describe the bug**
A clear and concise description of what the bug is:

When you run the command ./kill or die to a mod. It error out in console a weird class error. 

**To Reproduce**
1. Just die to a mob or get do ./kill and it will pop up in error

**Expected behavior**
A clear and concise description of what you expected to happen:

I would think not to error out with the weird class. Not sure. 

**Screenshots**
If applicable, add screenshots to help explain your problem:

https://gyazo.com/b534e7c82c2451d2a3888b9af876fc8b

https://gyazo.com/77d2a66306f10be5a9f7b3b2bf2b725b

Info (please complete the following information):

Mod Name: Just the standard version on manga

Mod Version: 1.15.2

Magma Version: forge-1.15.2-31.2.23-0e8d2fe-installer.jar
--
OS: Ubuntu 20

**Comment by jahangir6969** [comment]
Same error when it comes to going into the nether portal as well: 

https://gyazo.com/eab3011c782c5e9f8930752466c8efa2

https://hastebin.com/tirefuhula.cs

**Comment by Hexeption** [comment]
Fixed in 45ea75b997ead008adc5c851f9863ee7b2e83819
